#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fincific17
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FinDev3")]
	public partial class Fin17DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttbFinCard(tbFinCard instance);
    partial void UpdatetbFinCard(tbFinCard instance);
    partial void DeletetbFinCard(tbFinCard instance);
    partial void InserttbFinCardPrefix(tbFinCardPrefix instance);
    partial void UpdatetbFinCardPrefix(tbFinCardPrefix instance);
    partial void DeletetbFinCardPrefix(tbFinCardPrefix instance);
    #endregion
		
		public Fin17DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["FinDev3ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Fin17DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Fin17DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Fin17DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Fin17DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbFinCard> tbFinCards
		{
			get
			{
				return this.GetTable<tbFinCard>();
			}
		}
		
		public System.Data.Linq.Table<tbFinCardPrefix> tbFinCardPrefixes
		{
			get
			{
				return this.GetTable<tbFinCardPrefix>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbFinCard")]
	public partial class tbFinCard : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _FinKey;
		
		private string _FinNameEN;
		
		private EntitySet<tbFinCardPrefix> _tbFinCardPrefixes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFinKeyChanging(string value);
    partial void OnFinKeyChanged();
    partial void OnFinNameENChanging(string value);
    partial void OnFinNameENChanged();
    #endregion
		
		public tbFinCard()
		{
			this._tbFinCardPrefixes = new EntitySet<tbFinCardPrefix>(new Action<tbFinCardPrefix>(this.attach_tbFinCardPrefixes), new Action<tbFinCardPrefix>(this.detach_tbFinCardPrefixes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinKey", DbType="NVarChar(12) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string FinKey
		{
			get
			{
				return this._FinKey;
			}
			set
			{
				if ((this._FinKey != value))
				{
					this.OnFinKeyChanging(value);
					this.SendPropertyChanging();
					this._FinKey = value;
					this.SendPropertyChanged("FinKey");
					this.OnFinKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinNameEN", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FinNameEN
		{
			get
			{
				return this._FinNameEN;
			}
			set
			{
				if ((this._FinNameEN != value))
				{
					this.OnFinNameENChanging(value);
					this.SendPropertyChanging();
					this._FinNameEN = value;
					this.SendPropertyChanged("FinNameEN");
					this.OnFinNameENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbFinCard_tbFinCardPrefix", Storage="_tbFinCardPrefixes", ThisKey="FinKey", OtherKey="FinKey")]
		public EntitySet<tbFinCardPrefix> tbFinCardPrefixes
		{
			get
			{
				return this._tbFinCardPrefixes;
			}
			set
			{
				this._tbFinCardPrefixes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tbFinCardPrefixes(tbFinCardPrefix entity)
		{
			this.SendPropertyChanging();
			entity.tbFinCard = this;
		}
		
		private void detach_tbFinCardPrefixes(tbFinCardPrefix entity)
		{
			this.SendPropertyChanging();
			entity.tbFinCard = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbFinCardPrefix")]
	public partial class tbFinCardPrefix : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _FinKey;
		
		private string _MinPrefix;
		
		private string _MaxPrefix;
		
		private System.Nullable<byte> _MinDigitLen;
		
		private System.Nullable<byte> _MaxDigitLen;
		
		private System.Nullable<System.DateTime> _WhenStart;
		
		private System.Nullable<System.DateTime> _WhenEnd;
		
		private string _ValidationAlgorithm;
		
		private EntityRef<tbFinCard> _tbFinCard;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnFinKeyChanging(string value);
    partial void OnFinKeyChanged();
    partial void OnMinPrefixChanging(string value);
    partial void OnMinPrefixChanged();
    partial void OnMaxPrefixChanging(string value);
    partial void OnMaxPrefixChanged();
    partial void OnMinDigitLenChanging(System.Nullable<byte> value);
    partial void OnMinDigitLenChanged();
    partial void OnMaxDigitLenChanging(System.Nullable<byte> value);
    partial void OnMaxDigitLenChanged();
    partial void OnWhenStartChanging(System.Nullable<System.DateTime> value);
    partial void OnWhenStartChanged();
    partial void OnWhenEndChanging(System.Nullable<System.DateTime> value);
    partial void OnWhenEndChanged();
    partial void OnValidationAlgorithmChanging(string value);
    partial void OnValidationAlgorithmChanged();
    #endregion
		
		public tbFinCardPrefix()
		{
			this._tbFinCard = default(EntityRef<tbFinCard>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FinKey", DbType="NVarChar(12) NOT NULL", CanBeNull=false)]
		public string FinKey
		{
			get
			{
				return this._FinKey;
			}
			set
			{
				if ((this._FinKey != value))
				{
					if (this._tbFinCard.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFinKeyChanging(value);
					this.SendPropertyChanging();
					this._FinKey = value;
					this.SendPropertyChanged("FinKey");
					this.OnFinKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinPrefix", DbType="NVarChar(50)")]
		public string MinPrefix
		{
			get
			{
				return this._MinPrefix;
			}
			set
			{
				if ((this._MinPrefix != value))
				{
					this.OnMinPrefixChanging(value);
					this.SendPropertyChanging();
					this._MinPrefix = value;
					this.SendPropertyChanged("MinPrefix");
					this.OnMinPrefixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxPrefix", DbType="NVarChar(50)")]
		public string MaxPrefix
		{
			get
			{
				return this._MaxPrefix;
			}
			set
			{
				if ((this._MaxPrefix != value))
				{
					this.OnMaxPrefixChanging(value);
					this.SendPropertyChanging();
					this._MaxPrefix = value;
					this.SendPropertyChanged("MaxPrefix");
					this.OnMaxPrefixChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MinDigitLen", DbType="TinyInt")]
		public System.Nullable<byte> MinDigitLen
		{
			get
			{
				return this._MinDigitLen;
			}
			set
			{
				if ((this._MinDigitLen != value))
				{
					this.OnMinDigitLenChanging(value);
					this.SendPropertyChanging();
					this._MinDigitLen = value;
					this.SendPropertyChanged("MinDigitLen");
					this.OnMinDigitLenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxDigitLen", DbType="TinyInt")]
		public System.Nullable<byte> MaxDigitLen
		{
			get
			{
				return this._MaxDigitLen;
			}
			set
			{
				if ((this._MaxDigitLen != value))
				{
					this.OnMaxDigitLenChanging(value);
					this.SendPropertyChanging();
					this._MaxDigitLen = value;
					this.SendPropertyChanged("MaxDigitLen");
					this.OnMaxDigitLenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WhenStart", DbType="Date")]
		public System.Nullable<System.DateTime> WhenStart
		{
			get
			{
				return this._WhenStart;
			}
			set
			{
				if ((this._WhenStart != value))
				{
					this.OnWhenStartChanging(value);
					this.SendPropertyChanging();
					this._WhenStart = value;
					this.SendPropertyChanged("WhenStart");
					this.OnWhenStartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WhenEnd", DbType="Date")]
		public System.Nullable<System.DateTime> WhenEnd
		{
			get
			{
				return this._WhenEnd;
			}
			set
			{
				if ((this._WhenEnd != value))
				{
					this.OnWhenEndChanging(value);
					this.SendPropertyChanging();
					this._WhenEnd = value;
					this.SendPropertyChanged("WhenEnd");
					this.OnWhenEndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ValidationAlgorithm", DbType="NVarChar(12)")]
		public string ValidationAlgorithm
		{
			get
			{
				return this._ValidationAlgorithm;
			}
			set
			{
				if ((this._ValidationAlgorithm != value))
				{
					this.OnValidationAlgorithmChanging(value);
					this.SendPropertyChanging();
					this._ValidationAlgorithm = value;
					this.SendPropertyChanged("ValidationAlgorithm");
					this.OnValidationAlgorithmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tbFinCard_tbFinCardPrefix", Storage="_tbFinCard", ThisKey="FinKey", OtherKey="FinKey", IsForeignKey=true)]
		public tbFinCard tbFinCard
		{
			get
			{
				return this._tbFinCard.Entity;
			}
			set
			{
				tbFinCard previousValue = this._tbFinCard.Entity;
				if (((previousValue != value) 
							|| (this._tbFinCard.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tbFinCard.Entity = null;
						previousValue.tbFinCardPrefixes.Remove(this);
					}
					this._tbFinCard.Entity = value;
					if ((value != null))
					{
						value.tbFinCardPrefixes.Add(this);
						this._FinKey = value.FinKey;
					}
					else
					{
						this._FinKey = default(string);
					}
					this.SendPropertyChanged("tbFinCard");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
