<?xml version="1.0" encoding="utf-8"?><Database Name="finDev4" EntityNamespace="Fincific.Data" ContextNamespace="Fincific.Data" Class="FinancificDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=lin.arvixe.com;Initial Catalog=finDev4;Persist Security Info=True;User ID=FinDev" SettingsObjectName="Fincific.Data.Properties.Settings" SettingsPropertyName="finDev4ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AspNetUsers" Member="AspNetUsers">
    <Type Name="AspNetUser">
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="EmailConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SecurityStamp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumberConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TwoFactorEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LockoutEndDateUtc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LockoutEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AccessFailedCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="AspNetUser_Profile" Member="Profiles" ThisKey="Id" OtherKey="AspNetUserId" Type="Profile" />
    </Type>
  </Table>
  <Table Name="dbo.Profile" Member="Profiles">
    <Type Name="Profile">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AspNetUserId" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(144)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(144)" CanBeNull="true" />
      <Column Name="NickName" Type="System.String" DbType="NVarChar(144)" CanBeNull="true" />
      <Association Name="AspNetUser_Profile" Member="AspNetUser" ThisKey="AspNetUserId" OtherKey="Id" Type="AspNetUser" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GlAccount" Member="GlAccounts">
    <Type Name="GlAccount">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Number" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="AccountTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BalanceTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ConsolidateToAccountId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="GlAccount_GlAccount" Member="GlAccounts" ThisKey="Id" OtherKey="ConsolidateToAccountId" Type="GlAccount" />
      <Association Name="GlAccount_GlAccountDetail" Member="GlAccountDetails" ThisKey="Id" OtherKey="GlAccountId" Type="GlAccountDetail" />
      <Association Name="GlAccount_GlAccount" Member="GlAccount1" ThisKey="ConsolidateToAccountId" OtherKey="Id" Type="GlAccount" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GlAccountDetail" Member="GlAccountDetails">
    <Type Name="GlAccountDetail">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GlAccountId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FiscalYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FiscalPeriod" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Actual" Type="System.Decimal" DbType="Decimal(38,19)" CanBeNull="true" />
      <Column Name="Budget" Type="System.Decimal" DbType="Decimal(38,19)" CanBeNull="true" />
      <Association Name="GlAccount_GlAccountDetail" Member="GlAccount" ThisKey="GlAccountId" OtherKey="Id" Type="GlAccount" IsForeignKey="true" />
      <Association Name="SmPeriodConversion_GlAccountDetail" Member="SmPeriodConversion" ThisKey="FiscalYear,FiscalPeriod" OtherKey="FiscalYear,FiscalPeriod" Type="SmPeriodConversion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SmPeriodConversion" Member="SmPeriodConversions">
    <Type Name="SmPeriodConversion">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FiscalYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FiscalPeriod" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FromDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ThruDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GlClosed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ApClosed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="ArClosed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="SmPeriodConversion_GlAccountDetail" Member="GlAccountDetails" ThisKey="FiscalYear,FiscalPeriod" OtherKey="FiscalYear,FiscalPeriod" Type="GlAccountDetail" />
    </Type>
  </Table>
</Database>